theme = "gruvbox"
# theme = "github_dark_dimmed"
# theme = "hex_steel"

[editor]
line-number = "relative"
bufferline = "multiple"
idle-timeout = 0
# rainbow-brackets = true

[editor.lsp]
display-messages = true
# display-inlay-hints = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
right = ["diagnostics","version-control", "selections", "file-encoding", "file-type"]

[editor.soft-wrap]
enable = true
